### ISSUE TITLE
Polina not install on Windows 7 via npm

### ISSUE THREAD

**Issue by MikeBazhenov** [LiveTex/Node-Polina#10]
Npm debug log

http://yadi.sk/d/XefWb3RaJ6LHb

**Comment by valeriakononenko** [comment]
Попробуйте установить <a href="http://gnuwin32.sourceforge.net/packages/make.htm">это</a>.

**Comment by MikeBazhenov** [comment]
@divergence082 Make стоит в системе, процесс установки рушится на livetex-tools
